### ISSUE TITLE
Device EOL - M5STACK ATOM RS-485 Kit

### ISSUE THREAD

**Issue by Jackman3005** [lanwin/esphome_samsung_ac#104]
The device you link to in the instructions is [no longer purchasable](https://shop.m5stack.com/products/atom-rs485-kit?variant=34787900194980).

Is there a suitable alternative? Would the alternative require any alterations in the setup instructions?

Thanks in advance!

**Comment by Jackman3005** [comment]
Would this be suitable?

https://shop.m5stack.com/products/atomic-rs485-base

**Comment by lanwin** [comment]
Yes of course. 

That seems to be a bug in the docs. The kit is usually a combination between the RS-485 base and an M5Stack ATOM. But they can be purchased separately. I will change the docs here.
