### ISSUE TITLE
[NASA] Fan Speed

### ISSUE THREAD

**Issue by bzumik1** [lanwin/esphome_samsung_ac#11]
Hi, I am opening this issue to track the progress on controlling the fan speed of NASA devices. Currently It seems it is not supported.

**Comment by bzumik1** [comment]
Hi, I have tried to record some logs when I change the fan speed using IR remote controller. I did so at around **11:35:00 (+-10s)** on indoor unit with address **20.00.00**. So check the logs between **11:35:00-11:40:00** Hopefully it will help


[esp-samsung-ac-fanspeed.log](https://github.com/lanwin/esphome_samsung_ac/files/12790958/esp-samsung-ac-fanspeed.log)

**Comment by lanwin** [comment]
Thank you. I already started to impl this. But could not spend much time with it yet.

**Comment by bzumik1** [comment]
Perfect, if there would be anything I could help, just drop me a message.

**Comment by lanwin** [comment]
Fanmode is now implemented. Not sure if it works correctly in any case. Happy testing!

**Comment by bzumik1** [comment]
Thanks, let me redeploy the firmware and test it.

**Comment by bzumik1** [comment]
Hi, not sure if I might be doing something wrong, but even after multiple redeployments and deleting caches I do not see the fun speed.

**Comment by lanwin** [comment]
Sorry ists fixed now.

**Comment by bzumik1** [comment]
Thank you, I can confirm it works now.

**Comment by bzumik1** [comment]
Hi @lanwin is the order of fun speed options something you need to change?

**Comment by lanwin** [comment]
No from what I see I can not change that. The order seems to come from ESPHome itself.

**Comment by bzumik1** [comment]
Thx for checking
