### ISSUE TITLE
[NASA] Blades Direction

### ISSUE THREAD

**Issue by bzumik1** [lanwin/esphome_samsung_ac#12]
Hi, I am opening this to add support for setting the blades direction on indoor units. This would probably also cover special modes for blades such as "Long Wind" etc.

**Comment by bzumik1** [comment]
Hi @lanwin, I can imagine you have a lot of other work besides this project, but would it be possible to create some tracker on what you are features are you currently working on?

**Comment by mbo18** [comment]
Hi!

Here are debug logs from my HVAC when changing swing mode:
- At 17:35:00: vertical 
- At 17:35:29: horizontal
- At 17:36:02: fix
- At 17:36:21: all

[Swing mode.txt](https://github.com/lanwin/esphome_samsung_ac/files/13638428/Swing.mode.txt)

Thank you

**Comment by lanwin** [comment]
@mbo18 thank you! That will help. But don't expect a fast change. My time is pretty limited.
