### ISSUE TITLE
[NASA] Automatic Cleaning

### ISSUE THREAD

**Issue by bzumik1** [lanwin/esphome_samsung_ac#121]
Hello all,

I'd like to propose the addition of a toggle switch in this ESPHome integration for controlling the auto-cleaning function of air conditioning units. This feature allows the AC to continue running in fan-only mode for a few minutes after being turned off. Its primary purpose is to prevent the buildup of smells and mold inside the unit.

Currently, I can manage this functionality using the SmartThings HA integration along with a WiFi kit connected to my AC system. I believe this would be a valuable addition for others who wish to maintain their AC units more effectively.

I'm open to contribute to this feature by assisting with testing or exploring potential methods for enabling this functionality.

**Comment by hnykda** [comment]
I tried to turn on `debug_log_messages: true`, go to smarth things, air conditioner options and turn on/off `Auto clean`. But I haven't found anything in the logs with the code 0x4042. 

[logs_ac-control-beta_logs.txt](https://github.com/user-attachments/files/16244923/logs_ac-control-beta_logs.txt)

**Comment by kst84** [comment]
@lanwin Autoclean is when you turn the AC off while in cool mode, it will turn off cooling and for several minutes it will just use fan to remove all humidity leftover before completely shutting down the device. It's easy controllable via Smarthings app. Hope that is also controllable via NASA alongside beeping that someone mentioned in different issue.

**Comment by hnykda** [comment]
The latter! There is a toggle in the app and it remembers it.

Under the three dots here:
![image](https://github.com/user-attachments/assets/5dace165-8354-4cdc-897b-17624626f293)

you can set beep, auto clean, ...
![image](https://github.com/user-attachments/assets/5980c12e-f902-4e04-9fc6-fc67cf023b0f)

and it remembers the option.

**Comment by hnykda** [comment]
It's a detail, of course, but it would enable me to get rid of smart things entirely. Beep sound is on the remote as well as in this app, the auto clean only in the app and not remote.

**Comment by kst84** [comment]
Yeah, same here I would love to ditch SmartThings.

**Comment by hnykda** [comment]
Btw. I don't want to pollute this, but solution to this _might_ be similar to being able to turn off/on the LED Light (Lighting in the app at the screenshot above). 

I am confused by the fact that it's not visible in the logs - I would expect the API would somehow use NASA under the hood (and NASA being the only "API" to talk to the metal hardware stuff), but apparently not?

**Comment by brazoayeye** [comment]
> I am confused by the fact that it's not visible in the logs - I would expect the API would somehow use NASA under the hood (and NASA being the only "API" to talk to the metal hardware stuff), but apparently not?

Structures are not logged, if i remember right only length is logged . Maybe your info Is hidden there. I also sae that  packet Number often skips values, i don't know if It Is normal

**Comment by hnykda** [comment]
Yeah, also don't know 🤷 . Not sure where to go next, so keeping it as is.

**Comment by mchiriciuc** [comment]
Look for message 0x4111 for Auto Clean status
