### ISSUE TITLE
[NASA] Logging Devices on Bus

### ISSUE THREAD

**Issue by bzumik1** [lanwin/esphome_samsung_ac#17]
Currently the log for connected devices looks like this:

```log
[13:50:47][C][samsung_ac:107]: registered devices: 20.00.00, 20.00.01
[13:50:47][C][samsung_ac:122]: known indoor devices: 20.00.00, 20.00.01, 62.00.8f
[13:50:47][C][samsung_ac:123]: known outdoor devices: 10.00.00
```

I would rename the "known devices" to "Discovered devices" also it would be nice to start the log with capital letter at beginning to keep it consistent with other log messages. Also please check that my WiFi controller was put to indoor devices category, it would be nice to put it separately in "Other devices" or you can even put it to correct category based on the AddressClass [here](https://github.com/lanwin/esphome_samsung_ac/blob/main/components/samsung_ac/nasa.h).

P.S. is there some way how to set priority on the issue? This is very, very, very low priority 😄

**Comment by lanwin** [comment]
If you open another 20 issues ... then we should think about a priority system :D

**Comment by bzumik1** [comment]
Totally agree 😄. I thought there was at least some upvote mechanism on GitHub, but I do not see it. Maybe that is something optional and needs to be allowed for the repository; I'm not sure.

P.S. Please don't get discouraged by the number of issues; I am just opening them as I find some things that could be improved so they can be fixed later. Unfortunately, I do not know how to code ESPHome components, so I cannot help there. But if there is anything you think I can assist with, please let me know.

**Comment by bzumik1** [comment]
By the way, maybe it would be great to have a roadmap in README.md so we could see what the developer (currently just you) is working on.

**Comment by lanwin** [comment]
Is now fixed.

**Comment by bzumik1** [comment]
Checked and looks good, thx for implementation.

<img width="1038" alt="image" src="https://github.com/lanwin/esphome_samsung_ac/assets/32042186/9cf9bb94-0d46-4a61-b754-e7963c61fc77">
