### ISSUE TITLE
[NASA] can read but not control | Wind-Free Elite AR09TXCAAWKNEU/X

### ISSUE THREAD

**Issue by bulior** [lanwin/esphome_samsung_ac#178]
Hey,

I have an issue that i can read but can´t controll my AR09TXCAAWKNEU/X.
The ESP is reading the status correctly and will be updated if i change the mode on the AC with remote control but not from esp side (Webinterface)

Do you have an idea how to handle this model with esp ?
Or is there are an tutorial how to decode the HEX for an AC ?

Thanks ;)

<img width="1773" alt="image" src="https://github.com/user-attachments/assets/2f057b38-b98e-4bc7-94ec-2d52f47c0a95">

<details>
<summary>ESPHome Config:</summary>

esphome:
  name: samsung_ac
  friendly_name: Climate

esp32:
  board: m5stack-atom

web_server:
  port: 80

logger:
  level: INFO
  logs:
    component: ERROR # Remove the "Your component takes to long to respond warning"

Assistant
api:
  

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

uart:
  tx_pin: GPIO19   # Use GPIO26 for ATOM Tail485 
  rx_pin: GPIO22   # Use GPIO32 for ATOM Tail485
  baud_rate: 9600
  parity: EVEN

external_components:
  - source: github://lanwin/esphome_samsung_ac@main # use @main if you want the latest development (possibly unstable?)
    components: [samsung_ac]

samsung_ac:
  capabilities:
    vertical_swing: true
    horizontal_swing: true
    presets:
      quiet: true
      fast: true
      windfree: true
      sleep: true
  

  debug_log_messages: true

  debug_log_messages_raw: true

  non_nasa_keepalive: false

  devices:
    - address: "20.00.00"
      climate:
        name: "Haven room AC"
      room_temperature:
        name: "Haven room AC temperature"
      target_temperature:
        name: "Haven room AC target temperature"
      power:
        name: "Haven room AC power"
      mode:
        name: "Haven room AC mode"
      room_humidity:
        name: "Haven room AC humidity"
      room_temperature_offset: -1

</details>

**Comment by lanwin** [comment]
Hi, that is a known problem and its tracked here https://github.com/lanwin/esphome_samsung_ac/issues/127

**Comment by lanwin** [comment]
What you can do to help is to try https://github.com/lanwin/esphome_samsung_ac/discussions/66 and check if you can control your AC via Samsung SNET software.

**Comment by lanwin** [comment]
But please report your findings to the other issue.
