### ISSUE TITLE
[NASA] Can not disable swing modes for AC (neither horizontal nor vertical)

### ISSUE THREAD

**Issue by laszloh** [lanwin/esphome_samsung_ac#187]
Since the PR #169 horizontal_swing can not be disabled by yaml. The device capabilities do not have any effect any more:

```yaml
      capabilities: 
        vertical_swing: true
        horizontal_swing: false
```

result:
![image](https://github.com/user-attachments/assets/9d2b99af-83e9-41af-a0d1-a552479d3f94)

<br/>

The problem arises from the change in [__init__.py](https://github.com/lanwin/esphome_samsung_ac/blob/a26e8b06b666d2b85d7f67202fc13aa84f176e0d/components/samsung_ac/__init__.py#L286) line 286:

```py
        if capabilities.get(CONF_CAPABILITIES_VERTICAL_SWING):
            cg.add(var_dev.set_supports_vertical_swing(True))

        if capabilities.get(CONF_CAPABILITIES_HORIZONTAL_SWING):
            cg.add(var_dev.set_supports_horizontal_swing(True))
```

With this change, `set_supports_xxxxx_swing` is only called when the CONF_CAPABILITIES_xxxxx is `True`. If the capability is false, `set_supports_xxxx_swing` is never called.

Following the code,  `supports_xxxxx_swing_` can now only be `true` since the initialization value in `samsung_ac_device.h` is also `true` (see line 481 in samsung_ac_device.h). 

A solution would be to set the initialization values for `supports_horizontal_swing_` and `supports_vertical_swing_` to `false`.

**Comment by omerfaruk-aran** [comment]
Hello,

We have prepared a PR to resolve issue #187 regarding the handling of horizontal and vertical swing control. The fix ensures that both true and false values are properly passed from the YAML configuration.

You can find the related PR [here](https://github.com/lanwin/esphome_samsung_ac/pull/193).

We've tested the solution, and it works as expected. Please see the attached image from the test results:

![image](https://github.com/user-attachments/assets/cdf34a87-7dee-4355-b5a5-db721339bde5)

Thank you for your patience, and feel free to test it on your setup!

Best regards,
