### ISSUE TITLE
connection alternative

### ISSUE THREAD

**Issue by KrzysztofJ1976** [lanwin/esphome_samsung_ac#19]
Hi
 good job. One air conditioner is already connected, but I have a problem with the other one. Do I need to connect to the indoor air conditioning unit? Can I connect the cable between the outdoor and indoor units? because I have difficult access to the F1 and F2 connectors. Kris

**Comment by lanwin** [comment]
As far as I know that did not matter. I have a cable from each indoor unit to the outdoor unit and joined them all there. But you should also be able to connect the other indoor unit to the already working one.

**Comment by KrzysztofJ1976** [comment]
ok, thanks for the info, I'll try to connect to this cable next week.
