### ISSUE TITLE
[Non-NASA] Most UART messages aren't decoded

### ISSUE THREAD

**Issue by deece** [lanwin/esphome_samsung_ac#24]
I'm trying to get a Non-NASA system up and running, as I'm replacing a (now abandoned!) MIM-H02 Wifi interface.

It looks like it can't parse the incoming messages, except for one brief moment, immediately after power cycling the AC.

I've attached the logs & config. I am on commit c505fdd0fcb9863bc40a4f95c090c9cfc9431f6e

I did try at 2400 baud, but no messages at all were decoded, even after power cycling.

I've also tried disabling the Wifi Kit option via the control panel settings, but the behaviour is the same.

[logs_ac_rear_logs.txt](https://github.com/lanwin/esphome_samsung_ac/files/13195557/logs_ac_rear_logs.txt)
[ac_rear.yaml.txt](https://github.com/lanwin/esphome_samsung_ac/files/13195559/ac_rear.yaml.txt)

**Comment by lanwin** [comment]
Hi deece, sorry for the late reply but I was on vacation. 

Did you try to switch F1/F2?

**Comment by deece** [comment]
Ah, sorry, I didn't see y

**Comment by deece** [comment]
That did it! I could have sworn I tried swapping the line, but clearly I was mistaken. Thanks for the help.
