### ISSUE TITLE
Errors during compiling 

### ISSUE THREAD

**Issue by joloman2** [lanwin/esphome_samsung_ac#26]
hi im trying to compile but im getting errors could you help me 

[error_log.txt](https://github.com/lanwin/esphome_samsung_ac/files/13257767/error_log.txt)
[Config.yaml.txt](https://github.com/lanwin/esphome_samsung_ac/files/13257768/Config.yaml.txt)

**Comment by lanwin** [comment]
I expect that you found the error and the problem is gone. So please reopen when you need more help.
