### ISSUE TITLE
[NASA] WindFree Mode

### ISSUE THREAD

**Issue by bzumik1** [lanwin/esphome_samsung_ac#3]
Would it be possible to add WindFree mode?

**Comment by lanwin** [comment]
I think that would be possible. But the Term WindFree did not exists on protocol level. Maybe it hides between the other control option are its called differently there. 

So basically I did not figured it out yet und I am also not sure whats the best way to integrate it in ESPHome.

**Comment by bzumik1** [comment]
I have just ordered the RS485 adapter so when it arrives I can help you to find out the name for this option. I guess what when I turn the WindFree option using wi-fi kit on the same bus we should be able to figure out what command it sent.

**Comment by lucassant95** [comment]
This project is AWESOME! I'm buying the adapter and step down modules to start using this ASAP! I have 3 units of Samsung wind free ACs and was wondering how to make them connected to my smart home. I'll try this repo that looks like the best alternative than using IR remotes. Do you have a telegram group or something?

**Comment by bzumik1** [comment]
There seem to be nice HW from MStack if you like nice packaging. https://github.com/lanwin/esphome_samsung_ac/issues/4

**Comment by lanwin** [comment]
Its pretty funny. Windfree seems to be called alternative_mode on the protocol stack side. Can not spend much time currently in it. But it shouldnt be hard.

**Comment by bzumik1** [comment]
That sounds great! Please keep us posted on progress and let us now if any help from our side is needed.

**Comment by bzumik1** [comment]
Hi @lanwin, I got the HW and it is now working for me. Please let me know how can I help you to get the **WindFree** mode to the code base. I am also happy to help with testing etc.

**Comment by bzumik1** [comment]
Hi @lanwin, I have tried to record some logs when I turn on the WindFree mode using IR remote controller. I did so at around **11:25:00 (+-10s)** on indoor unit with address **20.00.00**. Hopefully it will help

[esp-samsung-ac-windfree.log](https://github.com/lanwin/esphome_samsung_ac/files/12790897/esp-samsung-ac-windfree.log)

P.S. for someone else who would like to record logs here is command I have used `esphome run esp-samsung-ac.yaml --device OTA > esp-samsung-ac-windfree.log`

**Comment by bzumik1** [comment]
Hi @lanwin sorry to bother you, is there any update for this feature? In case you would need my help please just let me know.

**Comment by bzumik1** [comment]
Ok no problem 🙂

**Comment by mantiscr** [comment]
Hi,
I developed an alternative solution on the F3, F4 side, just saw your repo and wanted to share this.
Extra Functions (40 60 _xx_)
_00_ All Off
_03_ Turbo (Refer to user manual for usage)
_06_ Long Reach (Refer to user manual for usage)
_09_ Windfree (Refer to user manual for usage)

(PS. i m just looking for turning off the indoor unit sound, as far as i see it can be changed only from wireless controller.)
