### ISSUE TITLE
nasa.h const values and naming issue

### ISSUE THREAD

**Issue by PeterOnDrums** [lanwin/esphome_samsung_ac#34]
Hi,

in esphome_samsung_ac/components/samsung_ac/nasa.h
the const values and also some of the strings
are somewhat confusing starting from line 33:

            **BoradcastCS** = 0xB3,
            BroadcastControlAndSetLayer = **0xB3**,
            BroadcastModuleLayer = 0xB4,
            **BoradcastCSM** = 0xB7,
            BroadcastLocalLayer = 0xB8,
            BroadcastCSML = 0xBF,
            **Undefiend** = 0xFF,

I am not familiar with github on how to **edit** this. I don't want to mess up anything.
Are You able to "repair" the values and strings ?

Cheers, Peter

**Comment by PeterOnDrums** [comment]
Yes, but also this "Boradcast" instead of "Broadcast" thing .. ;-)

**Comment by lanwin** [comment]
LOL I copied them over from Samsung SNET app...didnt noticed that. Thank. Its now fixed.

**Comment by PeterOnDrums** [comment]
Thanks a lot - also for Your fast response !
Cheers, Peter
