### ISSUE TITLE
[NASA] Temperature differs from the reported indoor temperature

### ISSUE THREAD

**Issue by mbo18** [lanwin/esphome_samsung_ac#35]
Hi!

I have a Samsung Windfree AR12TXCAAWKNEU with is working fine with your code but I have an issue with the temperature which differs from the one reported by my HVAC: 22.5°C using this code, 20°C using Samsung APP or the smartthings integration in HA.

From ESPHome log:

>[23:04:57][W][samsung_nasa:479]: s:20.00.00 d:b0.00.ff VAR_in_temp_room_f 22.500000
[23:04:57][D][sensor:094]: 'Temperature': Sending state 22.50000 °C with 1 decimals of accuracy
[23:04:57][D][climate:380]: 'Salon' - Sending state:
[23:04:57][D][climate:383]:   Mode: HEAT
[23:04:57][D][climate:388]:   Fan Mode: AUTO
[23:04:57][D][climate:403]:   Current Temperature: 22.50°C
[23:04:57][D][climate:409]:   Target Temperature: 19.00°C
[23:05:07][W][samsung_nasa:500]: s:20.00.00 d:b3.00.ff ENUM_in_operation_power on
[23:05:07][D][climate:380]: 'Salon' - Sending state:
[23:05:07][D][climate:383]:   Mode: HEAT
[23:05:07][D][climate:388]:   Fan Mode: AUTO
[23:05:07][D][climate:403]:   Current Temperature: 22.50°C
[23:05:07][D][climate:409]:   Target Temperature: 19.00°C
[23:05:07][W][samsung_nasa:506]: s:20.00.00 d:b3.00.ff ENUM_in_operation_mode 4
[23:05:07][D][select:015]: 'Mode': Sending state Heat (index 4)
[23:05:07][D][climate:380]: 'Salon' - Sending state:
[23:05:07][D][climate:383]:   Mode: HEAT
[23:05:07][D][climate:388]:   Fan Mode: AUTO
[23:05:07][D][climate:403]:   Current Temperature: 22.50°C
[23:05:08][D][climate:409]:   Target Temperature: 19.00°C
[23:05:08][W][samsung_nasa:494]: s:20.00.00 d:b3.00.ff ENUM_in_state_humidity_percent 44
[23:05:08][D][sensor:094]: 'Humidity': Sending state 44.00000 % with 0 decimals of accuracy

**Comment by lanwin** [comment]
Hi mbo18 thanks for reporting this. 

Can you please redeploy your version and add this option to your yaml config:

```
samsung_ac:
  debug_log_messages_raw: true
```

This will print the raw messages to console. 

Please let that run 15 seconds and the copy and paste the logs from that 15 seconds into here. 
Please also paste the current temp from ESPHome and from Samsung APP within that time range.

This could help to solve that problem.

**Comment by bzumik1** [comment]
Hi, I am also experiencing this issue, for me the difference was not so big though. Will also check it from my side.

**Comment by mbo18** [comment]
Please find attached log and temp as requested.

Please note that now that I have enable debug messages, I can't disable it. I've tried removing the line from the conf and set it to false without success.

<img width="508" alt="Capture d’écran 2023-12-05 à 09 58 44" src="https://github.com/lanwin/esphome_samsung_ac/assets/12999535/7cfb6970-ab14-42b0-a870-63e2ab70e05a">

[logs_salon-hvac_run.txt](https://github.com/lanwin/esphome_samsung_ac/files/13557659/logs_salon-hvac_run.txt)

**Comment by lanwin** [comment]
Can you please check if the Smartthings value inst simply the target temperature? The only 19° value I see in your logs is from the target temperature variable.

**Comment by mbo18** [comment]
I don't think so. Target temperature is set to 19 and is fixed. Also, the HVAC displays sometimes 20°, sometimes 19°

From the smartthings integration:
<img width="339" alt="Capture d’écran 2023-12-05 à 10 28 29" src="https://github.com/lanwin/esphome_samsung_ac/assets/12999535/7750e6e3-39b8-4bd4-8cfa-a6d1393ad980">

Temperature measurement is equal to currently from the climate entity.

**Comment by lanwin** [comment]
Could you please take a log when temp is 20° or change the target temp in example to 18°?

**Comment by mbo18** [comment]
See log attached.

I've changed the target temp to 18 at [12:48:36] and back to 19 at [12:48:57]
[logs_salon-hvac_logs.txt](https://github.com/lanwin/esphome_samsung_ac/files/13559625/logs_salon-hvac_logs.txt)

**Comment by mbo18** [comment]
And now with target temp set to 20° and indoor temp reported as 20°C by Smartthings
[logs_salon-hvac_logs(1).txt](https://github.com/lanwin/esphome_samsung_ac/files/13559666/logs_salon-hvac_logs.1.txt)

**Comment by mbo18** [comment]
Re-did it, target temp is set to 20, inside temp is reported as 21 by Samsung
<img width="975" alt="Capture d’écran 2023-12-05 à 13 31 47" src="https://github.com/lanwin/esphome_samsung_ac/assets/12999535/8b3e46c2-df39-4b95-9f2b-573aaf12b22a">

[logs_salon-hvac_logs(4).txt](https://github.com/lanwin/esphome_samsung_ac/files/13560088/logs_salon-hvac_logs.4.txt)

**Comment by lanwin** [comment]
Hmm I am not sure where that 2° gap came from. I could imaging that this is some sort of correction since most AC's are attached near the ceiling where its more hot then on the ground. 

@bzumik1 can you please check what the difference is for you? 

@mbo18 did the target temperature match? Did Smartthings have the same value als ESPHome and if you set the target temp in Smarttings did ESPHome also shows the same value?

**Comment by bzumik1** [comment]
Hi @lanwin will check it today or tomorrow.

**Comment by mbo18** [comment]
Hi lanwin,

Yes the target temperature match. I have the same value from ESPHome, Smartthings and the device's screen. It all updates in a second when changed.

I think that I will create a template sensor in ESPHome with a calibrate_linear filter.

**Comment by bzumik1** [comment]
Hi @lanwin, the difference is 0,5°C on one indoor unit and 1,7°C on another (both mounted at same height). I am trying to get the data to Grafana and compare the temperature which I am getting from smarthings and the one from this. The target temperature is same on both.

**Comment by bzumik1** [comment]
> Hi lanwin,
> 
> Yes the target temperature match. I have the same value from ESPHome, Smartthings and the device's screen. It all updates in a second when changed.
> 
> I think that I will create a template sensor in ESPHome with a calibrate_linear filter.

For now this seems like reasonable solution, but we should allow the calibration in this component it self. It is quite strange though because per my understanding these data would be shown on wall panel so do not understand why there is the difference. Can't we be reading different values?

**Comment by mbo18** [comment]
I think that Samsung is simulating the indoor temperature. The sensor is on the device at 2m+ but this does not represent the real room temperature.
The temperature we get seems to be very precise but the temperature from samsung is vague (adapted to the display and not precise because not the real temperature but an approximation). I may be wrong :)
<img width="496" alt="Capture d’écran 2023-12-08 à 10 59 23" src="https://github.com/lanwin/esphome_samsung_ac/assets/12999535/b8a441b6-7200-48e6-a877-6b947922d8f4">

**Comment by mbo18** [comment]
So I’m unable to do something on the esphome side as the current temperature has no id and I don’t know how to get the temperature. More over it would be best to being able to change it for the climate component. Maybe add a way to modify the temperature using lambda?

For anyone interested, the formula is: 
indoor temp = current temperature|int - 2

**Comment by lanwin** [comment]
@bzumik1 has you done more comparison with your data?

**Comment by bzumik1** [comment]
Hi, sorry didn't have time for that. I have it in my called though.

**Comment by mbo18** [comment]
I've added 2 more m5stack and now my 3 indoor units are locally connected!

Regarding temperature, I have slightly the same result. Sometimes its -2 or -3°. I did not find the real formula used by samsung.

<img width="998" alt="Capture d’écran 2024-01-10 à 16 54 16" src="https://github.com/lanwin/esphome_samsung_ac/assets/12999535/9049f8b9-c4c1-4be3-82c0-d6113f646f9f">

**Comment by lanwin** [comment]
Do you have 3 different outdoor devices with an indoor device each? Or one outdoor device and 3 indoor device?

**Comment by lanwin** [comment]
The configuration now has room_temperature_offset to correct the reported value. Please look into the example.yaml
