### ISSUE TITLE
[NASA] Add quiet mode

### ISSUE THREAD

**Issue by mbo18** [lanwin/esphome_samsung_ac#41]
Hi!

Is it possible to add "Quiet" mode?

Debug log attached:
- At 16:55:36 (fan_mode_real 13) = quiet mode activated (from auto)
- At 16:55:47/48 (fan_mode_real 11) = back to auto

Thank you

[quiet mode.txt](https://github.com/lanwin/esphome_samsung_ac/files/13638372/quiet.mode.txt)

**Comment by lanwin** [comment]
I think it will be possible. Can you tell me with indoor device you have? I will try if its possible to detect of the device have a quiet mode or not.

But don't expect a fast change. My time is pretty limited.

**Comment by mbo18** [comment]
I know what limited time is, no pressure :)
The quiet mode is the only feature I miss in order to not use the smartthings, that’s why I opened this FR. 

I have 3 Samsung HVAC Wind-Free Elite R32. Models are : AR09TXCAAWKNEU (2.5kW) and AR12TXCAAWKNEU (3.5kW). There is an ESP with this code only on the last one currently but I have ordered two m5stack atom for the others :)
