### ISSUE TITLE
Another controller on network NASA

### ISSUE THREAD

**Issue by bzumik1** [lanwin/esphome_samsung_ac#5]
Can this be used with another controller connected on the communication bus? I have wifi kit and I would like to use that one till we migrate all features to ESPHome.

**Comment by lanwin** [comment]
Technically I see no reason against it. The protocol basically works like an event bus where every message can be received by every consumer.

**Comment by bzumik1** [comment]
Thanks for confirmation.

**Comment by bzumik1** [comment]
I have just installed both SAMSUNG WiFi Kit as well as ESPHome based controller and both works just fine, I even can see the address of the SAMSUNG WiFi Kit displayed under indoor units.

<img width="1025" alt="image" src="https://github.com/lanwin/esphome_samsung_ac/assets/32042186/07014fae-9e7c-4dca-98b7-80190b650c23">

In my case the address is 62.00.8f

**Comment by lanwin** [comment]
> I have just installed both SAMSUNG WiFi Kit as well as ESPHome based controller and both works just fine, I even can see the address of the SAMSUNG WiFi Kit displayed under indoor units.
> <img alt="image" width="1025" src="https://user-images.githubusercontent.com/32042186/272304348-07014fae-9e7c-4dca-98b7-80190b650c23.png">
> 
> In my case the address is 62.00.8f

That is now fixed
