### ISSUE TITLE
Support for **09/12AVH** Model

### ISSUE THREAD

**Issue by lucassant95** [lanwin/esphome_samsung_ac#8]
Hey folks! Unfortunately upon installation I encountered a problem where the version of my AC doesn't have a F1/F2 port. Only a C port! I don't quite know if It is possible to start working on a integration for this model since It doesn't look to follow the standards of this project. Let me know if I can help in anything! Tks :D

**Comment by bzumik1** [comment]
Hi, what is product number of your AC? I can not find anything under "samsung 09/12AVH"

**Comment by lucassant95** [comment]
Sorry, It was the reference in the Manual. The model is AR12AVHABWKNAZ

**Comment by lanwin** [comment]
Its pretty hard to say. From Google it seems your device is sold in Brasil right? Maybe Samsung simply needs to use different naming in some countries. 

But I guess it still uses two wires? One would make no sens. 

What you could do is to buy a simple RS485 USB devices (they should be expensive) and check if you could get any data with Samsungs SNET 1 or 2 software (you could find it via google). If that works, this component should also work.

**Comment by lucassant95** [comment]
Yes! I'm from Brasil haha
But indeed it's only 1 Cable for communication and two for power. The communication only has a C as label. The fourth cabe seems to be ground![Screenshot_20231001_082504_YouTube.jpg](https://github.com/lanwin/esphome_samsung_ac/assets/69677812/6aa79bc5-3468-4a71-9ffe-5f10f101d0e4)

**Comment by lanwin** [comment]
I would guess that the second wire is the ground connector on the left side. Did you have a multimeter? Then you need to make sure that there is no hight voltage on the connection between ground and C. 

But be careful! On 1(N) and 2(L) should have 110/223 volt.

**Comment by lanwin** [comment]
For now I close this issue. If you have further questions. Please open a new discussion.
